### ISSUE TITLE
Output has degraded significantly!

### ISSUE THREAD

**Issue by designgrande** [jeffshek/writeup-frontend#143]
I think you have disabled the "large" or "1.5B" (mega xl, I believe).

I "used" to use this tool to save me like an hour while creating content, but the output is less coherent and sometimes just repeats the same text I entered.

I am all up for pro version like $9 or $15 per month to access the larger models, but please reenable the bigger model.

**Comment by jeffshek** [comment]
@designgrande hey - yeah, i disabled the large because i didn't feel like the output was that good (tradeoff was speed) ... i sort of got frustrated at it and turned it off. 

i'm hoping to learn a bit more about model compression and redo large (and medium) to run faster tbh
